### PR TITLE
Persist currentModule context within page refresh

### PR DESCRIPTION
**Pull request by davidbgomes**
### :pushpin: References

-   **Issue:** Closes#86948jvz2 [Fix module context on the first list of each module](https://app.clickup.com/t/86948jvz2)

### :memo: Implementation
- Use session storage to persist currentModule within page refreshes

### CODE REVIEW

**Review by MiquelAdell — APPROVED** [review]

**Review by 9sneha-n — CHANGES_REQUESTED** [review]

**Comment by davidbgomes** [comment]
Thanks @9sneha-n , good points, addressed that.

**Review by 9sneha-n — APPROVED** [review]

**Comment by 9sneha-n** [comment]
@davidbgomes  looks good to me. Lets ensure we have the code in the right layer by waiting for @xurxodev's review.

**Comment by 9sneha-n** [comment]
@xurxodev The PR is merged , but please provide your review whenever possible and we will address it in a new PR.

**Review by xurxodev — COMMENTED** [review]
@9sneha-n I've reviewed the code.

I understand the problem that to refresh the page the context of the current module is loss, and you use sessionStorage to persist it and to avoid it.

In this case for me also is a presentation concern because data layer doesn't know anything about this context.

Not for now, but if you start to use sessionStorage in different parts of the app, then I would create a wrapper for window.sessionStorage named uiCache or whatever to centralize future changes about cache in one unique point.

**Comment by 9sneha-n** [comment]
> oesn't know anything about

@xurxodev Thank you for the review. Noted, if we use the session storage further, will ensure that we create an abstraction. Thank you!

**Pull request merged**
